import React, { createContext, useContext, useState, useEffect, useRef } from 'react';

const LanguageContext = createContext(null);

export const LANGUAGES = [
  {
    "code": "en",
    "label": "English",
    "englishLabel": "English",
    "state": "All India",
    "flag": "🇬🇧"
  },
  {
    "code": "hi",
    "label": "हिन्दी",
    "englishLabel": "Hindi",
    "state": "North / Central India (UP, MP, Bihar, Rajasthan, Delhi)",
    "flag": "🇮🇳"
  },
  {
    "code": "gu",
    "label": "ગુજરાતી",
    "englishLabel": "Gujarati",
    "state": "Gujarat",
    "flag": "🇮🇳"
  },
  {
    "code": "mr",
    "label": "मराठी",
    "englishLabel": "Marathi",
    "state": "Maharashtra & Goa",
    "flag": "🇮🇳"
  },
  {
    "code": "pa",
    "label": "ਪੰਜਾਬੀ",
    "englishLabel": "Punjabi",
    "state": "Punjab & Haryana",
    "flag": "🇮🇳"
  },
  {
    "code": "bn",
    "label": "বাংলা",
    "englishLabel": "Bengali",
    "state": "West Bengal & Tripura",
    "flag": "🇮🇳"
  },
  {
    "code": "ta",
    "label": "தமிழ்",
    "englishLabel": "Tamil",
    "state": "Tamil Nadu & Puducherry",
    "flag": "🇮🇳"
  },
  {
    "code": "te",
    "label": "తెలుగు",
    "englishLabel": "Telugu",
    "state": "Andhra Pradesh & Telangana",
    "flag": "🇮🇳"
  },
  {
    "code": "kn",
    "label": "ಕನ್ನಡ",
    "englishLabel": "Kannada",
    "state": "Karnataka",
    "flag": "🇮🇳"
  },
  {
    "code": "ml",
    "label": "മലയാളം",
    "englishLabel": "Malayalam",
    "state": "Kerala & Lakshadweep",
    "flag": "🇮🇳"
  },
  {
    "code": "or",
    "label": "ଓଡ଼ିଆ",
    "englishLabel": "Odia",
    "state": "Odisha",
    "flag": "🇮🇳"
  },
  {
    "code": "as",
    "label": "অসমীয়া",
    "englishLabel": "Assamese",
    "state": "Assam",
    "flag": "🇮🇳"
  },
  {
    "code": "ur",
    "label": "اردو",
    "englishLabel": "Urdu",
    "state": "Jammu & Kashmir, Telangana, UP",
    "flag": "🇮🇳"
  },
  {
    "code": "mai",
    "label": "मैथिली",
    "englishLabel": "Maithili",
    "state": "Bihar & Jharkhand",
    "flag": "🇮🇳"
  },
  {
    "code": "bho",
    "label": "भोजपुरी",
    "englishLabel": "Bhojpuri",
    "state": "Bihar & Eastern UP",
    "flag": "🇮🇳"
  },
  {
    "code": "gom",
    "label": "कोंकणी",
    "englishLabel": "Konkani",
    "state": "Goa & Coastal Karnataka",
    "flag": "🇮🇳"
  },
  {
    "code": "doi",
    "label": "डोगरी",
    "englishLabel": "Dogri",
    "state": "Jammu & Kashmir & Himachal",
    "flag": "🇮🇳"
  },
  {
    "code": "ne",
    "label": "नेपाली",
    "englishLabel": "Nepali",
    "state": "Sikkim & North Bengal",
    "flag": "🇮🇳"
  },
  {
    "code": "sd",
    "label": "سنڌي / सिंधी",
    "englishLabel": "Sindhi",
    "state": "Gujarat & Rajasthan",
    "flag": "🇮🇳"
  },
  {
    "code": "sa",
    "label": "संस्कृतम्",
    "englishLabel": "Sanskrit",
    "state": "Uttarakhand & Heritage",
    "flag": "🇮🇳"
  }
];

export const translations = {
  "en": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "hi": {
    "brandTitle": "AnnDhara",
    "brandTagline": "भारतीय किसानों के लिए एआई बाज़ार बुद्धिमत्ता और उचित मूल्य खोज",
    "footerNetwork": "एआई-संचालित मांग-से-वितरण कृषि नेटवर्क",
    "footerSub": "पारदर्शी खेत-से-उपभोक्ता नेटवर्क",
    "liveGovData": "लाइव सरकारी डेटा",
    "cachedAgmarknet": "कैश्ड एग्मार्कनेट",
    "manage": "प्रबंधित करें",
    "refreshData": "डेटा रीफ्रेश करें",
    "synchronizing": "सिंक हो रहा है...",
    "signOut": "लॉग आउट",
    "selectLanguage": "भाषा चुनें",
    "searchLanguage": "राज्य या भाषा खोजें...",
    "tabDashboard": "मेरा डैशबोर्ड",
    "tabOverview": "अवलोकन और परिचय",
    "tabFarmerHub": "किसान और एफपीओ पोर्टल",
    "tabMarketplace": "खरीदार बाज़ार",
    "tabDemandForecast": "मांग और हीटमैप",
    "tabSmartMatch": "एआई स्मार्ट मिलान",
    "tabLogistics": "साझा लॉजिस्टिक्स",
    "tabFoodWaste": "अपव्यय रोकथाम",
    "tabFairPrice": "उचित मूल्य वक्र (Prophet)",
    "tabMandiCompare": "मंडी शुद्ध लाभ तुलना",
    "tabMarkupAnomaly": "रिटेल मार्कअप विसंगति जांच",
    "deepAnalyticsTitle": "गहन विश्लेषण और मंडी इंजन:",
    "farmerBadge": "🌾 किसान कमांड सेंटर",
    "farmerTitle": "किसान और एफपीओ उत्पादक कार्यक्षेत्र",
    "farmerDesc": "अपनी उपज के लिए विश्वसनीय उचित मूल्य प्राप्त करें, सीधे खरीदारों से जुड़ें और नुकसान से बचें।",
    "buyerBadge": "🛒 खरीदार डायरेक्ट हब",
    "buyerTitle": "खरीदार और खुदरा व्यापारी खरीद केंद्र",
    "buyerDesc": "सीधे खेत से ताजी उपज प्राप्त करें, अग्रिम आपूर्ति बुक करें और थोक ऑर्डर सुरक्षित करें।",
    "logisticsBadge": "🚚 वाहन और रूट ग्रिड",
    "logisticsTitle": "लॉजिस्टिक्स बेड़ा और प्रेषण कार्यक्षेत्र",
    "logisticsDesc": "साझा मार्गों, लाइव ट्रैकिंग और सुनिश्चित कमाई के साथ वाहनों को कुशलतापूर्वक संचालित करें।",
    "loggedInAs": "लॉग इन किया गया",
    "activeListings": "सक्रिय लिस्टिंग",
    "matchedBuyers": "जुड़े खरीदार",
    "avgPriceUplift": "औसत मूल्य वृद्धि",
    "availableListings": "उपलब्ध फसल लॉट",
    "nearbyFarms": "निकटवर्ती खेत",
    "avgProcurementSavings": "औसत खरीद बचत",
    "activeDispatches": "सक्रिय डिस्पैच",
    "onTimeRate": "समय पर डिलीवरी दर",
    "sharedFuelSavings": "साझा मार्ग ईंधन बचत",
    "commandPortalsHeading": "AnnDhara प्लेटफॉर्म कमांड पोर्टल",
    "commandPortalsSub": "रीयल-टाइम व्यापार संकेत, लाइव साझा रूट और खेत से सीधी आपूर्ति देखें",
    "directMarketTitle": "प्रत्यक्ष कृषि उपज बाज़ार",
    "directMarketDesc": "लाइव तस्वीरों, उचित मूल्य मानकों और फार्म-टू-फोर्क क्यूआर कोड के साथ 68+ सत्यापित किसानों की उपज देखें।",
    "openMarketplace": "बाज़ार खोलें",
    "sharedLogisticsTitle": "स्मार्ट साझा लॉजिस्टिक्स इंजन",
    "sharedLogisticsDesc": "निकटवर्ती ऑर्डरों को संयुक्त डिलीवरी में बदलें, खाली वाहन यात्रा घटाएं और 25% तक लागत बचाएं।",
    "openLogisticsGrid": "लॉजिस्टिक्स ग्रिड खोलें",
    "fairPriceTitle": "उचित मूल्य और बाज़ार बुद्धिमत्ता",
    "fairPriceDesc": "185 एग्मार्कनेट वस्तुओं के आधार पर प्रोफ़ेट एआई मूल्य पूर्वानुमान किसान और खरीदार दोनों को सुरक्षा प्रदान करते हैं।",
    "checkPriceBands": "मूल्य बैंड जांचें",
    "quickActionsTitle": "त्वरित कार्य",
    "actionAddHarvest": "फसल लिस्टिंग जोड़ें",
    "actionSeeDemand": "मांग पूर्वानुमान देखें",
    "actionBrowseProduce": "ताजी उपज ब्राउज़ करें",
    "actionMatchRequirement": "आवश्यकता का मिलान करें",
    "actionManageRoutes": "डिलीवरी रूट प्रबंधित करें",
    "actionReviewAssignments": "असाइनमेंट की समीक्षा करें",
    "liveDeliveryTitle": "लाइव ऑर्डर और डिलीवरी ट्रैकिंग",
    "myPurchasesTitle": "मेरी खरीदारी और लाइव ट्रैकिंग",
    "myFarmgateOrdersTitle": "मेरे खेत के ऑर्डर और पिकअप",
    "logisticsOpsTitle": "लॉजिस्टिक्स डिलीवरी संचालन और लाइव ट्रैकिंग",
    "incomingOrdersTab": "प्राप्त ऑर्डर और लॉजिस्टिक्स",
    "buyAndBookDelivery": "खरीदें और डिलीवरी बुक करें",
    "orderSuccessfullyPlaced": "ऑर्डर सफलतापूर्वक दर्ज किया गया!",
    "orderConfirmedDesc": "आपका ऑर्डर कन्फर्म हो गया है और लॉजिस्टिक्स डिस्पैच शुरू हो गया है।",
    "trackLiveDelivery": "लाइव डिलीवरी ट्रैक करें",
    "quickPostLocation": "लाइव चेकपॉइंट लोकेशन अपडेट करें:",
    "allCrops": "सभी फसलें",
    "connectingMsg": "AnnDhara फार्म-टू-मार्केट नेटवर्क से कनेक्ट हो रहा है...",
    "connectingSub": "मांग मॉडल, क्षेत्रीय हीटमैप और मंडी डेटा फीड प्रारंभ किए जा रहे हैं"
  },
  "gu": {
    "brandTitle": "AnnDhara",
    "brandTagline": "ભારતીય ખેડૂતો માટે એઆઈ બજાર વિશ્લેષણ અને યોગ્ય ભાવ શોધ",
    "footerNetwork": "એઆઈ-સંચાલિત માંગ-થી-ડિલિવરી કૃષિ નેટવર્ક",
    "footerSub": "પારદર્શક ખેતર-થી-ગ્રાહક નેટવર્ક",
    "liveGovData": "લાઈવ સરકારી ડેટા",
    "cachedAgmarknet": "કેશ્ડ એગમાર્કનેટ",
    "manage": "મેનેજ કરો",
    "refreshData": "ડેટા રિફ્રેશ કરો",
    "synchronizing": "સિંક થઈ રહ્યું છે...",
    "signOut": "સાઇન આઉટ",
    "selectLanguage": "ભાષા પસંદ કરો",
    "searchLanguage": "રાજ્ય અથવા ભાષા શોધો...",
    "tabDashboard": "મારું ડેશબોર્ડ",
    "tabOverview": "વિહંગાવલોકન અને પરિચય",
    "tabFarmerHub": "ખેડૂત અને એફપીઓ પોર્ટલ",
    "tabMarketplace": "ખરીદદાર બજાર",
    "tabDemandForecast": "માંગ અને હીટમેપ",
    "tabSmartMatch": "એઆઈ સ્માર્ટ મેચિંગ",
    "tabLogistics": "શેર્ડ લોજિસ્ટિક્સ",
    "tabFoodWaste": "બગાડ નિવારણ",
    "tabFairPrice": "ભાવ વળાંક આગાહી (Prophet)",
    "tabMandiCompare": "મંડી ચોખ્ખો નફો તુલના",
    "tabMarkupAnomaly": "રિટેલ ભાવ વિસંગતતા તપાસ",
    "deepAnalyticsTitle": "ઊંડાણપૂર્વક વિશ્લેષણ અને મંડી એન્જિન:",
    "farmerBadge": "🌾 ઉત્પાદક કમાન્ડ સેન્ટર",
    "farmerTitle": "ખેડૂત અને એફપીઓ કાર્યક્ષેત્ર",
    "farmerDesc": "તમારી ફસલ માટે યોગ્ય અને વિશ્વસનીય ભાવ મેળવો, સીધા ખરીદદારો સાથે જોડાઓ અને નુકસાનથી બચો.",
    "buyerBadge": "🛒 ખરીદદાર ડાયરેક્ટ હબ",
    "buyerTitle": "ખરીદદાર અને વેપારી ખરીદી કેન્દ્ર",
    "buyerDesc": "સીધા ખેતરમાંથી તાજી ઉપજ મેળવો, અગાઉથી ઓર્ડર બુક કરો અને ફાયદાકારક ખરીદી કરો.",
    "logisticsBadge": "🚚 વાહન અને રૂટ ગ્રીડ",
    "logisticsTitle": "વાહન કાફલો અને ડિસ્પેચ કાર્યક્ષેત્ર",
    "logisticsDesc": "શેર્ડ મલ્ટી-ફાર્મ રૂટ્સ, લાઈવ જીપીએસ ટ્રેકિંગ અને ગેરંટીકૃત કમાણી સાથે વાહનો કાર્યક્ષમ રીતે ચલાવો.",
    "loggedInAs": "લૉગ ઇન કરેલ વપરાશકર્તા",
    "activeListings": "સક્રિય લિસ્ટિંગ",
    "matchedBuyers": "જોડાયેલ ખરીદદારો",
    "avgPriceUplift": "સરેરાશ ભાવ વધારો",
    "availableListings": "ઉપલબ્ધ પાક લોટ",
    "nearbyFarms": "નજીકના ખેતરો",
    "avgProcurementSavings": "સરેરાશ ખરીદી બચત",
    "activeDispatches": "સક્રિય ટ્રિપ્સ",
    "onTimeRate": "સમયસર ડિલિવરી દર",
    "sharedFuelSavings": "શેર્ડ રૂટ ઇંધણ બચત",
    "commandPortalsHeading": "AnnDhara પ્લેટફોર્મ કમાન્ડ પોર્ટલ",
    "commandPortalsSub": "રિયલ-ટાઇમ વેપાર સંકેત, લાઈવ શેર્ડ રૂટ્સ અને ખેતરથી સીધો પુરવઠો જુઓ",
    "directMarketTitle": "સીધું ખેત ઉપજ બજાર",
    "directMarketDesc": "લાઈવ ફોટા, યોગ્ય ભાવ માપદંડ અને ખેતર-થી-થાલી ક્યૂઆર કોડ સાથે 68+ પ્રમાણિત ખેડૂતોની ઉપજ જુઓ.",
    "openMarketplace": "બજાર ખોલો",
    "sharedLogisticsTitle": "સ્માર્ટ શેર્ડ લોજિસ્ટિક્સ એન્જિન",
    "sharedLogisticsDesc": "નજીકના ઓર્ડરોને જોડીને સંયુક્ત ડિલિવરી કરો, ખાલી વાહન દોડ ઘટાડો અને 25% સુધી ખર્ચ બચાવો.",
    "openLogisticsGrid": "લોજિસ્ટિક્સ ખોલો",
    "fairPriceTitle": "યોગ્ય ભાવ અને બજાર વિશ્લેષણ",
    "fairPriceDesc": "185 એગમાર્કનેટ પાકના આધારે પ્રોફેટ એઆઈ ભાવ આગાહી ખેડૂત અને ગ્રાહક બંનેને યોગ્ય સુરક્ષા આપે છે.",
    "checkPriceBands": "ભાવ આગાહી તપાસો",
    "quickActionsTitle": "ઝડપી ક્રિયાઓ",
    "actionAddHarvest": "ફસલ લિસ્ટ કરો",
    "actionSeeDemand": "માંગ આગાહી જુઓ",
    "actionBrowseProduce": "તાજી ફસલ જુઓ",
    "actionMatchRequirement": "જરૂરિયાત મેચ કરો",
    "actionManageRoutes": "ડિલિવરી રૂટ જુઓ",
    "actionReviewAssignments": "ઓર્ડર્સ તપાસો",
    "liveDeliveryTitle": "લાઈવ ઓર્ડર અને ડિલિવરી ટ્રેકિંગ",
    "myPurchasesTitle": "મારી ખરીદી અને લાઈવ ટ્રેકિંગ",
    "myFarmgateOrdersTitle": "મારા ખેતરના ઓર્ડર્સ અને પિકઅપ",
    "logisticsOpsTitle": "લોજિસ્ટિક્સ ડિલિવરી કામગીરી અને લાઈવ ટ્રેકિંગ",
    "incomingOrdersTab": "આવેલા ઓર્ડર્સ અને લોજિસ્ટિક્સ",
    "buyAndBookDelivery": "ખરીદો અને ડિલિવરી બુક કરો",
    "orderSuccessfullyPlaced": "ઓર્ડર સફળતાપૂર્વક બુક થયો!",
    "orderConfirmedDesc": "તમારો ઓર્ડર કન્ફર્મ થઈ ગયો છે અને ડિલિવરી શરૂ થઈ ગઈ છે.",
    "trackLiveDelivery": "લાઈવ ડિલિવરી ટ્રેક કરો",
    "quickPostLocation": "લાઈવ ચેકપોઇન્ટ લોકેશન અપડેટ કરો:",
    "allCrops": "બધા પાક",
    "connectingMsg": "AnnDhara ફાર્મ-ટુ-માર્કેટ નેટવર્ક સાથે કનેક્ટ થઈ રહ્યું છે...",
    "connectingSub": "માંગ મોડલ, પ્રાદેશિક હીટમેપ અને મંડી ડેટા શરૂ થઈ રહ્યા છે"
  },
  "mr": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "pa": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "bn": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "ta": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "te": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "kn": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "ml": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "or": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "as": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "ur": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "mai": {
    "brandTitle": "AnnDhara",
    "brandTagline": "भारतीय किसानों के लिए एआई बाज़ार बुद्धिमत्ता और उचित मूल्य खोज",
    "footerNetwork": "एआई-संचालित मांग-से-वितरण कृषि नेटवर्क",
    "footerSub": "पारदर्शी खेत-से-उपभोक्ता नेटवर्क",
    "liveGovData": "लाइव सरकारी डेटा",
    "cachedAgmarknet": "कैश्ड एग्मार्कनेट",
    "manage": "प्रबंधित करें",
    "refreshData": "डेटा रीफ्रेश करें",
    "synchronizing": "सिंक हो रहा है...",
    "signOut": "लॉग आउट",
    "selectLanguage": "भाषा चुनें",
    "searchLanguage": "राज्य या भाषा खोजें...",
    "tabDashboard": "मेरा डैशबोर्ड",
    "tabOverview": "अवलोकन और परिचय",
    "tabFarmerHub": "किसान और एफपीओ पोर्टल",
    "tabMarketplace": "खरीदार बाज़ार",
    "tabDemandForecast": "मांग और हीटमैप",
    "tabSmartMatch": "एआई स्मार्ट मिलान",
    "tabLogistics": "साझा लॉजिस्टिक्स",
    "tabFoodWaste": "अपव्यय रोकथाम",
    "tabFairPrice": "उचित मूल्य वक्र (Prophet)",
    "tabMandiCompare": "मंडी शुद्ध लाभ तुलना",
    "tabMarkupAnomaly": "रिटेल मार्कअप विसंगति जांच",
    "deepAnalyticsTitle": "गहन विश्लेषण और मंडी इंजन:",
    "farmerBadge": "🌾 किसान कमांड सेंटर",
    "farmerTitle": "किसान और एफपीओ उत्पादक कार्यक्षेत्र",
    "farmerDesc": "अपनी उपज के लिए विश्वसनीय उचित मूल्य प्राप्त करें, सीधे खरीदारों से जुड़ें और नुकसान से बचें।",
    "buyerBadge": "🛒 खरीदार डायरेक्ट हब",
    "buyerTitle": "खरीदार और खुदरा व्यापारी खरीद केंद्र",
    "buyerDesc": "सीधे खेत से ताजी उपज प्राप्त करें, अग्रिम आपूर्ति बुक करें और थोक ऑर्डर सुरक्षित करें।",
    "logisticsBadge": "🚚 वाहन और रूट ग्रिड",
    "logisticsTitle": "लॉजिस्टिक्स बेड़ा और प्रेषण कार्यक्षेत्र",
    "logisticsDesc": "साझा मार्गों, लाइव ट्रैकिंग और सुनिश्चित कमाई के साथ वाहनों को कुशलतापूर्वक संचालित करें।",
    "loggedInAs": "लॉग इन किया गया",
    "activeListings": "सक्रिय लिस्टिंग",
    "matchedBuyers": "जुड़े खरीदार",
    "avgPriceUplift": "औसत मूल्य वृद्धि",
    "availableListings": "उपलब्ध फसल लॉट",
    "nearbyFarms": "निकटवर्ती खेत",
    "avgProcurementSavings": "औसत खरीद बचत",
    "activeDispatches": "सक्रिय डिस्पैच",
    "onTimeRate": "समय पर डिलीवरी दर",
    "sharedFuelSavings": "साझा मार्ग ईंधन बचत",
    "commandPortalsHeading": "AnnDhara प्लेटफॉर्म कमांड पोर्टल",
    "commandPortalsSub": "रीयल-टाइम व्यापार संकेत, लाइव साझा रूट और खेत से सीधी आपूर्ति देखें",
    "directMarketTitle": "प्रत्यक्ष कृषि उपज बाज़ार",
    "directMarketDesc": "लाइव तस्वीरों, उचित मूल्य मानकों और फार्म-टू-फोर्क क्यूआर कोड के साथ 68+ सत्यापित किसानों की उपज देखें।",
    "openMarketplace": "बाज़ार खोलें",
    "sharedLogisticsTitle": "स्मार्ट साझा लॉजिस्टिक्स इंजन",
    "sharedLogisticsDesc": "निकटवर्ती ऑर्डरों को संयुक्त डिलीवरी में बदलें, खाली वाहन यात्रा घटाएं और 25% तक लागत बचाएं।",
    "openLogisticsGrid": "लॉजिस्टिक्स ग्रिड खोलें",
    "fairPriceTitle": "उचित मूल्य और बाज़ार बुद्धिमत्ता",
    "fairPriceDesc": "185 एग्मार्कनेट वस्तुओं के आधार पर प्रोफ़ेट एआई मूल्य पूर्वानुमान किसान और खरीदार दोनों को सुरक्षा प्रदान करते हैं।",
    "checkPriceBands": "मूल्य बैंड जांचें",
    "quickActionsTitle": "त्वरित कार्य",
    "actionAddHarvest": "फसल लिस्टिंग जोड़ें",
    "actionSeeDemand": "मांग पूर्वानुमान देखें",
    "actionBrowseProduce": "ताजी उपज ब्राउज़ करें",
    "actionMatchRequirement": "आवश्यकता का मिलान करें",
    "actionManageRoutes": "डिलीवरी रूट प्रबंधित करें",
    "actionReviewAssignments": "असाइनमेंट की समीक्षा करें",
    "liveDeliveryTitle": "लाइव ऑर्डर और डिलीवरी ट्रैकिंग",
    "myPurchasesTitle": "मेरी खरीदारी और लाइव ट्रैकिंग",
    "myFarmgateOrdersTitle": "मेरे खेत के ऑर्डर और पिकअप",
    "logisticsOpsTitle": "लॉजिस्टिक्स डिलीवरी संचालन और लाइव ट्रैकिंग",
    "incomingOrdersTab": "प्राप्त ऑर्डर और लॉजिस्टिक्स",
    "buyAndBookDelivery": "खरीदें और डिलीवरी बुक करें",
    "orderSuccessfullyPlaced": "ऑर्डर सफलतापूर्वक दर्ज किया गया!",
    "orderConfirmedDesc": "आपका ऑर्डर कन्फर्म हो गया है और लॉजिस्टिक्स डिस्पैच शुरू हो गया है।",
    "trackLiveDelivery": "लाइव डिलीवरी ट्रैक करें",
    "quickPostLocation": "लाइव चेकपॉइंट लोकेशन अपडेट करें:",
    "allCrops": "सभी फसलें",
    "connectingMsg": "AnnDhara फार्म-टू-मार्केट नेटवर्क से कनेक्ट हो रहा है...",
    "connectingSub": "मांग मॉडल, क्षेत्रीय हीटमैप और मंडी डेटा फीड प्रारंभ किए जा रहे हैं"
  },
  "bho": {
    "brandTitle": "AnnDhara",
    "brandTagline": "भारतीय किसानों के लिए एआई बाज़ार बुद्धिमत्ता और उचित मूल्य खोज",
    "footerNetwork": "एआई-संचालित मांग-से-वितरण कृषि नेटवर्क",
    "footerSub": "पारदर्शी खेत-से-उपभोक्ता नेटवर्क",
    "liveGovData": "लाइव सरकारी डेटा",
    "cachedAgmarknet": "कैश्ड एग्मार्कनेट",
    "manage": "प्रबंधित करें",
    "refreshData": "डेटा रीफ्रेश करें",
    "synchronizing": "सिंक हो रहा है...",
    "signOut": "लॉग आउट",
    "selectLanguage": "भाषा चुनें",
    "searchLanguage": "राज्य या भाषा खोजें...",
    "tabDashboard": "मेरा डैशबोर्ड",
    "tabOverview": "अवलोकन और परिचय",
    "tabFarmerHub": "किसान और एफपीओ पोर्टल",
    "tabMarketplace": "खरीदार बाज़ार",
    "tabDemandForecast": "मांग और हीटमैप",
    "tabSmartMatch": "एआई स्मार्ट मिलान",
    "tabLogistics": "साझा लॉजिस्टिक्स",
    "tabFoodWaste": "अपव्यय रोकथाम",
    "tabFairPrice": "उचित मूल्य वक्र (Prophet)",
    "tabMandiCompare": "मंडी शुद्ध लाभ तुलना",
    "tabMarkupAnomaly": "रिटेल मार्कअप विसंगति जांच",
    "deepAnalyticsTitle": "गहन विश्लेषण और मंडी इंजन:",
    "farmerBadge": "🌾 किसान कमांड सेंटर",
    "farmerTitle": "किसान और एफपीओ उत्पादक कार्यक्षेत्र",
    "farmerDesc": "अपनी उपज के लिए विश्वसनीय उचित मूल्य प्राप्त करें, सीधे खरीदारों से जुड़ें और नुकसान से बचें।",
    "buyerBadge": "🛒 खरीदार डायरेक्ट हब",
    "buyerTitle": "खरीदार और खुदरा व्यापारी खरीद केंद्र",
    "buyerDesc": "सीधे खेत से ताजी उपज प्राप्त करें, अग्रिम आपूर्ति बुक करें और थोक ऑर्डर सुरक्षित करें।",
    "logisticsBadge": "🚚 वाहन और रूट ग्रिड",
    "logisticsTitle": "लॉजिस्टिक्स बेड़ा और प्रेषण कार्यक्षेत्र",
    "logisticsDesc": "साझा मार्गों, लाइव ट्रैकिंग और सुनिश्चित कमाई के साथ वाहनों को कुशलतापूर्वक संचालित करें।",
    "loggedInAs": "लॉग इन किया गया",
    "activeListings": "सक्रिय लिस्टिंग",
    "matchedBuyers": "जुड़े खरीदार",
    "avgPriceUplift": "औसत मूल्य वृद्धि",
    "availableListings": "उपलब्ध फसल लॉट",
    "nearbyFarms": "निकटवर्ती खेत",
    "avgProcurementSavings": "औसत खरीद बचत",
    "activeDispatches": "सक्रिय डिस्पैच",
    "onTimeRate": "समय पर डिलीवरी दर",
    "sharedFuelSavings": "साझा मार्ग ईंधन बचत",
    "commandPortalsHeading": "AnnDhara प्लेटफॉर्म कमांड पोर्टल",
    "commandPortalsSub": "रीयल-टाइम व्यापार संकेत, लाइव साझा रूट और खेत से सीधी आपूर्ति देखें",
    "directMarketTitle": "प्रत्यक्ष कृषि उपज बाज़ार",
    "directMarketDesc": "लाइव तस्वीरों, उचित मूल्य मानकों और फार्म-टू-फोर्क क्यूआर कोड के साथ 68+ सत्यापित किसानों की उपज देखें।",
    "openMarketplace": "बाज़ार खोलें",
    "sharedLogisticsTitle": "स्मार्ट साझा लॉजिस्टिक्स इंजन",
    "sharedLogisticsDesc": "निकटवर्ती ऑर्डरों को संयुक्त डिलीवरी में बदलें, खाली वाहन यात्रा घटाएं और 25% तक लागत बचाएं।",
    "openLogisticsGrid": "लॉजिस्टिक्स ग्रिड खोलें",
    "fairPriceTitle": "उचित मूल्य और बाज़ार बुद्धिमत्ता",
    "fairPriceDesc": "185 एग्मार्कनेट वस्तुओं के आधार पर प्रोफ़ेट एआई मूल्य पूर्वानुमान किसान और खरीदार दोनों को सुरक्षा प्रदान करते हैं।",
    "checkPriceBands": "मूल्य बैंड जांचें",
    "quickActionsTitle": "त्वरित कार्य",
    "actionAddHarvest": "फसल लिस्टिंग जोड़ें",
    "actionSeeDemand": "मांग पूर्वानुमान देखें",
    "actionBrowseProduce": "ताजी उपज ब्राउज़ करें",
    "actionMatchRequirement": "आवश्यकता का मिलान करें",
    "actionManageRoutes": "डिलीवरी रूट प्रबंधित करें",
    "actionReviewAssignments": "असाइनमेंट की समीक्षा करें",
    "liveDeliveryTitle": "लाइव ऑर्डर और डिलीवरी ट्रैकिंग",
    "myPurchasesTitle": "मेरी खरीदारी और लाइव ट्रैकिंग",
    "myFarmgateOrdersTitle": "मेरे खेत के ऑर्डर और पिकअप",
    "logisticsOpsTitle": "लॉजिस्टिक्स डिलीवरी संचालन और लाइव ट्रैकिंग",
    "incomingOrdersTab": "प्राप्त ऑर्डर और लॉजिस्टिक्स",
    "buyAndBookDelivery": "खरीदें और डिलीवरी बुक करें",
    "orderSuccessfullyPlaced": "ऑर्डर सफलतापूर्वक दर्ज किया गया!",
    "orderConfirmedDesc": "आपका ऑर्डर कन्फर्म हो गया है और लॉजिस्टिक्स डिस्पैच शुरू हो गया है।",
    "trackLiveDelivery": "लाइव डिलीवरी ट्रैक करें",
    "quickPostLocation": "लाइव चेकपॉइंट लोकेशन अपडेट करें:",
    "allCrops": "सभी फसलें",
    "connectingMsg": "AnnDhara फार्म-टू-मार्केट नेटवर्क से कनेक्ट हो रहा है...",
    "connectingSub": "मांग मॉडल, क्षेत्रीय हीटमैप और मंडी डेटा फीड प्रारंभ किए जा रहे हैं"
  },
  "gom": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "doi": {
    "brandTitle": "AnnDhara",
    "brandTagline": "भारतीय किसानों के लिए एआई बाज़ार बुद्धिमत्ता और उचित मूल्य खोज",
    "footerNetwork": "एआई-संचालित मांग-से-वितरण कृषि नेटवर्क",
    "footerSub": "पारदर्शी खेत-से-उपभोक्ता नेटवर्क",
    "liveGovData": "लाइव सरकारी डेटा",
    "cachedAgmarknet": "कैश्ड एग्मार्कनेट",
    "manage": "प्रबंधित करें",
    "refreshData": "डेटा रीफ्रेश करें",
    "synchronizing": "सिंक हो रहा है...",
    "signOut": "लॉग आउट",
    "selectLanguage": "भाषा चुनें",
    "searchLanguage": "राज्य या भाषा खोजें...",
    "tabDashboard": "मेरा डैशबोर्ड",
    "tabOverview": "अवलोकन और परिचय",
    "tabFarmerHub": "किसान और एफपीओ पोर्टल",
    "tabMarketplace": "खरीदार बाज़ार",
    "tabDemandForecast": "मांग और हीटमैप",
    "tabSmartMatch": "एआई स्मार्ट मिलान",
    "tabLogistics": "साझा लॉजिस्टिक्स",
    "tabFoodWaste": "अपव्यय रोकथाम",
    "tabFairPrice": "उचित मूल्य वक्र (Prophet)",
    "tabMandiCompare": "मंडी शुद्ध लाभ तुलना",
    "tabMarkupAnomaly": "रिटेल मार्कअप विसंगति जांच",
    "deepAnalyticsTitle": "गहन विश्लेषण और मंडी इंजन:",
    "farmerBadge": "🌾 किसान कमांड सेंटर",
    "farmerTitle": "किसान और एफपीओ उत्पादक कार्यक्षेत्र",
    "farmerDesc": "अपनी उपज के लिए विश्वसनीय उचित मूल्य प्राप्त करें, सीधे खरीदारों से जुड़ें और नुकसान से बचें।",
    "buyerBadge": "🛒 खरीदार डायरेक्ट हब",
    "buyerTitle": "खरीदार और खुदरा व्यापारी खरीद केंद्र",
    "buyerDesc": "सीधे खेत से ताजी उपज प्राप्त करें, अग्रिम आपूर्ति बुक करें और थोक ऑर्डर सुरक्षित करें।",
    "logisticsBadge": "🚚 वाहन और रूट ग्रिड",
    "logisticsTitle": "लॉजिस्टिक्स बेड़ा और प्रेषण कार्यक्षेत्र",
    "logisticsDesc": "साझा मार्गों, लाइव ट्रैकिंग और सुनिश्चित कमाई के साथ वाहनों को कुशलतापूर्वक संचालित करें।",
    "loggedInAs": "लॉग इन किया गया",
    "activeListings": "सक्रिय लिस्टिंग",
    "matchedBuyers": "जुड़े खरीदार",
    "avgPriceUplift": "औसत मूल्य वृद्धि",
    "availableListings": "उपलब्ध फसल लॉट",
    "nearbyFarms": "निकटवर्ती खेत",
    "avgProcurementSavings": "औसत खरीद बचत",
    "activeDispatches": "सक्रिय डिस्पैच",
    "onTimeRate": "समय पर डिलीवरी दर",
    "sharedFuelSavings": "साझा मार्ग ईंधन बचत",
    "commandPortalsHeading": "AnnDhara प्लेटफॉर्म कमांड पोर्टल",
    "commandPortalsSub": "रीयल-टाइम व्यापार संकेत, लाइव साझा रूट और खेत से सीधी आपूर्ति देखें",
    "directMarketTitle": "प्रत्यक्ष कृषि उपज बाज़ार",
    "directMarketDesc": "लाइव तस्वीरों, उचित मूल्य मानकों और फार्म-टू-फोर्क क्यूआर कोड के साथ 68+ सत्यापित किसानों की उपज देखें।",
    "openMarketplace": "बाज़ार खोलें",
    "sharedLogisticsTitle": "स्मार्ट साझा लॉजिस्टिक्स इंजन",
    "sharedLogisticsDesc": "निकटवर्ती ऑर्डरों को संयुक्त डिलीवरी में बदलें, खाली वाहन यात्रा घटाएं और 25% तक लागत बचाएं।",
    "openLogisticsGrid": "लॉजिस्टिक्स ग्रिड खोलें",
    "fairPriceTitle": "उचित मूल्य और बाज़ार बुद्धिमत्ता",
    "fairPriceDesc": "185 एग्मार्कनेट वस्तुओं के आधार पर प्रोफ़ेट एआई मूल्य पूर्वानुमान किसान और खरीदार दोनों को सुरक्षा प्रदान करते हैं।",
    "checkPriceBands": "मूल्य बैंड जांचें",
    "quickActionsTitle": "त्वरित कार्य",
    "actionAddHarvest": "फसल लिस्टिंग जोड़ें",
    "actionSeeDemand": "मांग पूर्वानुमान देखें",
    "actionBrowseProduce": "ताजी उपज ब्राउज़ करें",
    "actionMatchRequirement": "आवश्यकता का मिलान करें",
    "actionManageRoutes": "डिलीवरी रूट प्रबंधित करें",
    "actionReviewAssignments": "असाइनमेंट की समीक्षा करें",
    "liveDeliveryTitle": "लाइव ऑर्डर और डिलीवरी ट्रैकिंग",
    "myPurchasesTitle": "मेरी खरीदारी और लाइव ट्रैकिंग",
    "myFarmgateOrdersTitle": "मेरे खेत के ऑर्डर और पिकअप",
    "logisticsOpsTitle": "लॉजिस्टिक्स डिलीवरी संचालन और लाइव ट्रैकिंग",
    "incomingOrdersTab": "प्राप्त ऑर्डर और लॉजिस्टिक्स",
    "buyAndBookDelivery": "खरीदें और डिलीवरी बुक करें",
    "orderSuccessfullyPlaced": "ऑर्डर सफलतापूर्वक दर्ज किया गया!",
    "orderConfirmedDesc": "आपका ऑर्डर कन्फर्म हो गया है और लॉजिस्टिक्स डिस्पैच शुरू हो गया है।",
    "trackLiveDelivery": "लाइव डिलीवरी ट्रैक करें",
    "quickPostLocation": "लाइव चेकपॉइंट लोकेशन अपडेट करें:",
    "allCrops": "सभी फसलें",
    "connectingMsg": "AnnDhara फार्म-टू-मार्केट नेटवर्क से कनेक्ट हो रहा है...",
    "connectingSub": "मांग मॉडल, क्षेत्रीय हीटमैप और मंडी डेटा फीड प्रारंभ किए जा रहे हैं"
  },
  "ne": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "sd": {
    "brandTitle": "AnnDhara",
    "brandTagline": "AI Market Intelligence & Fair Price Discovery for Indian Farmers",
    "footerNetwork": "AI-Powered Demand-to-Delivery Agricultural Network",
    "footerSub": "Transparent Farmgate-to-Fork Network",
    "liveGovData": "Live Gov Data",
    "cachedAgmarknet": "Cached Agmarknet",
    "manage": "Manage",
    "refreshData": "Refresh Data",
    "synchronizing": "Synchronizing...",
    "signOut": "Sign out",
    "selectLanguage": "Select Language",
    "searchLanguage": "Search state or language...",
    "tabDashboard": "My Dashboard",
    "tabOverview": "Overview & Pitch",
    "tabFarmerHub": "Farmer & FPO Portal",
    "tabMarketplace": "Buyer Marketplace",
    "tabDemandForecast": "Demand & Heatmap",
    "tabSmartMatch": "AI Smart Matching",
    "tabLogistics": "Shared Logistics",
    "tabFoodWaste": "Waste Prevention",
    "tabFairPrice": "Prophet Price Curve",
    "tabMandiCompare": "Mandi Net Profit Comparator",
    "tabMarkupAnomaly": "Retail Markup Anomaly Detector",
    "deepAnalyticsTitle": "Deep Analytics & Mandi Engines:",
    "farmerBadge": "🌾 Producer Command Center",
    "farmerTitle": "Farmer & FPO Producer Workspace",
    "farmerDesc": "Turn your harvest into dependable fair prices, connect with direct buyers, and eliminate distress sales.",
    "buyerBadge": "🛒 Buyer Direct Hub",
    "buyerTitle": "Buyer & Retailer Procurement Workspace",
    "buyerDesc": "Source fresh farmgate produce directly, lock pre-harvest supply, and plan bulk orders with confidence.",
    "logisticsBadge": "🚚 Fleet & Route Grid",
    "logisticsTitle": "Logistics Fleet & Dispatch Workspace",
    "logisticsDesc": "Keep vehicles moving efficiently with shared multi-farm routes, live tracking, and guaranteed earnings.",
    "loggedInAs": "Logged in as",
    "activeListings": "Active listings",
    "matchedBuyers": "Matched buyers",
    "avgPriceUplift": "Avg. price uplift",
    "availableListings": "Available listings",
    "nearbyFarms": "Nearby farms",
    "avgProcurementSavings": "Avg. procurement savings",
    "activeDispatches": "Active dispatches",
    "onTimeRate": "On-time rate",
    "sharedFuelSavings": "Shared route fuel savings",
    "commandPortalsHeading": "AnnDhara Platform Command Portals",
    "commandPortalsSub": "Explore real-time trade signals, live shared dispatch routes, and direct farmgate supply",
    "directMarketTitle": "Direct Farm Produce Marketplace",
    "directMarketDesc": "Browse 68+ verified farmer lots with live photographs, Fair Price benchmarks, and Farm-to-Fork QR traceability.",
    "openMarketplace": "Open Marketplace",
    "sharedLogisticsTitle": "Smart Shared Logistics Engine",
    "sharedLogisticsDesc": "Pool neighboring orders into unified delivery runs, eliminating empty return miles and lowering costs by up to 25%.",
    "openLogisticsGrid": "Open Logistics Grid",
    "fairPriceTitle": "Fair Price & Market Intelligence",
    "fairPriceDesc": "Prophet AI price forecasts calibrated against 185 Agmarknet commodities protect both farmers and buyers.",
    "checkPriceBands": "Check Price Bands",
    "quickActionsTitle": "Quick Workflow Actions",
    "actionAddHarvest": "Add a harvest listing",
    "actionSeeDemand": "See demand forecast",
    "actionBrowseProduce": "Browse fresh produce",
    "actionMatchRequirement": "Match a requirement",
    "actionManageRoutes": "Manage delivery routes",
    "actionReviewAssignments": "Review delivery assignments",
    "liveDeliveryTitle": "Live Orders & Delivery Tracking",
    "myPurchasesTitle": "My Purchases & Live Tracking",
    "myFarmgateOrdersTitle": "My Farmgate Orders & Pickups",
    "logisticsOpsTitle": "Logistics Delivery Operations & Live Tracking",
    "incomingOrdersTab": "Incoming Orders & Logistics",
    "buyAndBookDelivery": "Buy & Book Delivery",
    "orderSuccessfullyPlaced": "Order Successfully Placed!",
    "orderConfirmedDesc": "Your order has been confirmed and logistics dispatch has begun.",
    "trackLiveDelivery": "Track Live Delivery",
    "quickPostLocation": "Quick-Post Live Checkpoint Location:",
    "allCrops": "All Crops",
    "connectingMsg": "Connecting to AnnDhara Farm-to-Market Network...",
    "connectingSub": "Initializing demand models, regional heatmaps, and agricultural data feeds"
  },
  "sa": {
    "brandTitle": "AnnDhara",
    "brandTagline": "भारतीय किसानों के लिए एआई बाज़ार बुद्धिमत्ता और उचित मूल्य खोज",
    "footerNetwork": "एआई-संचालित मांग-से-वितरण कृषि नेटवर्क",
    "footerSub": "पारदर्शी खेत-से-उपभोक्ता नेटवर्क",
    "liveGovData": "लाइव सरकारी डेटा",
    "cachedAgmarknet": "कैश्ड एग्मार्कनेट",
    "manage": "प्रबंधित करें",
    "refreshData": "डेटा रीफ्रेश करें",
    "synchronizing": "सिंक हो रहा है...",
    "signOut": "लॉग आउट",
    "selectLanguage": "भाषा चुनें",
    "searchLanguage": "राज्य या भाषा खोजें...",
    "tabDashboard": "मेरा डैशबोर्ड",
    "tabOverview": "अवलोकन और परिचय",
    "tabFarmerHub": "किसान और एफपीओ पोर्टल",
    "tabMarketplace": "खरीदार बाज़ार",
    "tabDemandForecast": "मांग और हीटमैप",
    "tabSmartMatch": "एआई स्मार्ट मिलान",
    "tabLogistics": "साझा लॉजिस्टिक्स",
    "tabFoodWaste": "अपव्यय रोकथाम",
    "tabFairPrice": "उचित मूल्य वक्र (Prophet)",
    "tabMandiCompare": "मंडी शुद्ध लाभ तुलना",
    "tabMarkupAnomaly": "रिटेल मार्कअप विसंगति जांच",
    "deepAnalyticsTitle": "गहन विश्लेषण और मंडी इंजन:",
    "farmerBadge": "🌾 किसान कमांड सेंटर",
    "farmerTitle": "किसान और एफपीओ उत्पादक कार्यक्षेत्र",
    "farmerDesc": "अपनी उपज के लिए विश्वसनीय उचित मूल्य प्राप्त करें, सीधे खरीदारों से जुड़ें और नुकसान से बचें।",
    "buyerBadge": "🛒 खरीदार डायरेक्ट हब",
    "buyerTitle": "खरीदार और खुदरा व्यापारी खरीद केंद्र",
    "buyerDesc": "सीधे खेत से ताजी उपज प्राप्त करें, अग्रिम आपूर्ति बुक करें और थोक ऑर्डर सुरक्षित करें।",
    "logisticsBadge": "🚚 वाहन और रूट ग्रिड",
    "logisticsTitle": "लॉजिस्टिक्स बेड़ा और प्रेषण कार्यक्षेत्र",
    "logisticsDesc": "साझा मार्गों, लाइव ट्रैकिंग और सुनिश्चित कमाई के साथ वाहनों को कुशलतापूर्वक संचालित करें।",
    "loggedInAs": "लॉग इन किया गया",
    "activeListings": "सक्रिय लिस्टिंग",
    "matchedBuyers": "जुड़े खरीदार",
    "avgPriceUplift": "औसत मूल्य वृद्धि",
    "availableListings": "उपलब्ध फसल लॉट",
    "nearbyFarms": "निकटवर्ती खेत",
    "avgProcurementSavings": "औसत खरीद बचत",
    "activeDispatches": "सक्रिय डिस्पैच",
    "onTimeRate": "समय पर डिलीवरी दर",
    "sharedFuelSavings": "साझा मार्ग ईंधन बचत",
    "commandPortalsHeading": "AnnDhara प्लेटफॉर्म कमांड पोर्टल",
    "commandPortalsSub": "रीयल-टाइम व्यापार संकेत, लाइव साझा रूट और खेत से सीधी आपूर्ति देखें",
    "directMarketTitle": "प्रत्यक्ष कृषि उपज बाज़ार",
    "directMarketDesc": "लाइव तस्वीरों, उचित मूल्य मानकों और फार्म-टू-फोर्क क्यूआर कोड के साथ 68+ सत्यापित किसानों की उपज देखें।",
    "openMarketplace": "बाज़ार खोलें",
    "sharedLogisticsTitle": "स्मार्ट साझा लॉजिस्टिक्स इंजन",
    "sharedLogisticsDesc": "निकटवर्ती ऑर्डरों को संयुक्त डिलीवरी में बदलें, खाली वाहन यात्रा घटाएं और 25% तक लागत बचाएं।",
    "openLogisticsGrid": "लॉजिस्टिक्स ग्रिड खोलें",
    "fairPriceTitle": "उचित मूल्य और बाज़ार बुद्धिमत्ता",
    "fairPriceDesc": "185 एग्मार्कनेट वस्तुओं के आधार पर प्रोफ़ेट एआई मूल्य पूर्वानुमान किसान और खरीदार दोनों को सुरक्षा प्रदान करते हैं।",
    "checkPriceBands": "मूल्य बैंड जांचें",
    "quickActionsTitle": "त्वरित कार्य",
    "actionAddHarvest": "फसल लिस्टिंग जोड़ें",
    "actionSeeDemand": "मांग पूर्वानुमान देखें",
    "actionBrowseProduce": "ताजी उपज ब्राउज़ करें",
    "actionMatchRequirement": "आवश्यकता का मिलान करें",
    "actionManageRoutes": "डिलीवरी रूट प्रबंधित करें",
    "actionReviewAssignments": "असाइनमेंट की समीक्षा करें",
    "liveDeliveryTitle": "लाइव ऑर्डर और डिलीवरी ट्रैकिंग",
    "myPurchasesTitle": "मेरी खरीदारी और लाइव ट्रैकिंग",
    "myFarmgateOrdersTitle": "मेरे खेत के ऑर्डर और पिकअप",
    "logisticsOpsTitle": "लॉजिस्टिक्स डिलीवरी संचालन और लाइव ट्रैकिंग",
    "incomingOrdersTab": "प्राप्त ऑर्डर और लॉजिस्टिक्स",
    "buyAndBookDelivery": "खरीदें और डिलीवरी बुक करें",
    "orderSuccessfullyPlaced": "ऑर्डर सफलतापूर्वक दर्ज किया गया!",
    "orderConfirmedDesc": "आपका ऑर्डर कन्फर्म हो गया है और लॉजिस्टिक्स डिस्पैच शुरू हो गया है।",
    "trackLiveDelivery": "लाइव डिलीवरी ट्रैक करें",
    "quickPostLocation": "लाइव चेकपॉइंट लोकेशन अपडेट करें:",
    "allCrops": "सभी फसलें",
    "connectingMsg": "AnnDhara फार्म-टू-मार्केट नेटवर्क से कनेक्ट हो रहा है...",
    "connectingSub": "मांग मॉडल, क्षेत्रीय हीटमैप और मंडी डेटा फीड प्रारंभ किए जा रहे हैं"
  }
};

// Programmatic trigger for Google Translate
function setGoogleTranslateCookie(langCode) {
  try {
    const hostname = window.location.hostname;
    if (langCode === 'en') {
      // Clear cookie to restore default English
      document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
      document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=' + hostname + ';';
      document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=.' + hostname + ';';
    } else {
      const cookieVal = '/en/' + langCode;
      document.cookie = 'googtrans=' + cookieVal + '; path=/;';
      document.cookie = 'googtrans=' + cookieVal + '; path=/; domain=' + hostname + ';';
      document.cookie = 'googtrans=' + cookieVal + '; path=/; domain=.' + hostname + ';';
    }

    // Trigger Google Translate dropdown element if available
    const select = document.querySelector('.goog-te-combo');
    if (select) {
      select.value = langCode;
      select.dispatchEvent(new Event('change'));
    }
  } catch (e) {
    console.warn('Google Translate sync:', e);
  }
}

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    try {
      return (localStorage.getItem('anndhara_lang') || localStorage.getItem('anndhana_lang')) || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = (lang) => {
    setCurrentLanguage(lang);
    try {
      localStorage.setItem('anndhara_lang', lang);
    localStorage.setItem('anndhana_lang', lang);
    } catch (e) {
      console.error('Error saving language', e);
    }
    setGoogleTranslateCookie(lang);
  };

  // Sync with Google Translate on mount and when DOM elements appear
  useEffect(() => {
    setGoogleTranslateCookie(currentLanguage);

    // If Google Translate loads asynchronously after React mounts
    const checkInterval = setInterval(() => {
      const select = document.querySelector('.goog-te-combo');
      if (select && select.value !== currentLanguage) {
        setGoogleTranslateCookie(currentLanguage);
        clearInterval(checkInterval);
      }
    }, 500);

    const timer = setTimeout(() => clearInterval(checkInterval), 6000);
    return () => {
      clearInterval(checkInterval);
      clearTimeout(timer);
    };
  }, [currentLanguage]);

  const t = (key, fallback = '') => {
    const langDict = translations[currentLanguage] || translations.en;
    if (langDict && langDict[key] !== undefined) return langDict[key];
    if (translations.en && translations.en[key] !== undefined) return translations.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        languages: LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLanguage: 'en',
      setLanguage: () => { },
      t: (key, fallback = '') => (translations.en && translations.en[key]) || fallback || key,
      languages: LANGUAGES
    };
  }
  return context;
}
